---
- include_tasks:
    file: nftables.yml
    apply:
      tags: ["nftables"]
  when: nft_add_input_rule is not defined
  tags:
    - always

- include_tasks:
    file: input_rule.yml
    apply:
      tags: ["nftables"]
  when: nft_add_input_rule is defined
  tags:
    - always
