---
- name: Install nftables
  ansible.builtin.package:
    name: nftables
    state: present
    update_cache: true
  register: pkg_install_result
  until: pkg_install_result is success
  retries: 5
  delay: 10

- name: Install nftables
  ansible.builtin.package:
    name: python3-netaddr
    state: present
    update_cache: false
  register: pkg_install_result
  until: pkg_install_result is success
  retries: 5
  delay: 10

- name: Create include directories
  ansible.builtin.file:
    path: /etc/nftables.d/{{ item }}
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - ""
    - "pre"
    - "custom"
    - "post"

- name: Create main nftables configuration
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0644
  notify: ['Reload nftables service']

- name: Enable nftables Debian systemd service unit
  ansible.builtin.systemd:
    name: nftables
    enabled: true
  notify: ['Reload nftables service']

- name: Disable ufw service
  ansible.builtin.systemd:
    name: ufw
    enabled: false
    state: stopped
  failed_when: false

- name: Add pre templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/nftables.d/pre/{{ item | basename | regex_replace('.j2','') }}.nft"
    owner: root
    group: root
    mode: 0644
  loop: "{{ lookup('fileglob', 'templates/pre/*_*.j2', wantlist=True) }}"
  notify: ['Reload nftables service']

- name: Add post templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/nftables.d/post/{{ item | basename | regex_replace('.j2','') }}.nft"
    owner: root
    group: root
    mode: 0644
  loop: "{{ lookup('fileglob', 'templates/post/*_*.j2', wantlist=True) }}"
  notify: ['Reload nftables service']