---
- name: Converge
  hosts: all
  gather_facts: yes
  # pre_tasks:
  #   - debug:
  #       var: ansible_facts
  roles:
    - role: devopsworks.nftables
      nft_auto_whitelist: true
      nft_ansible_controllers:
        - 1.2.3.4
        - fe80::7aa5:15ce:1234:aaaa

    - role: devopsworks.nftables
      nft_add_input_rule:
        - protocol: 'udp'
          saddrs: [ '1.2.3.4', 'fe80::7aa5:15ce:1234:aaaa' ]
          dports: [ '33', '34' ]
          name: test
          weight: 12

    - role: devopsworks.nftables
      nft_add_input_rule:
        - protocol: 'udp'
          saddrs: [ '5.6.7.8', 'fe80::7aa5:15ce:5678:aaaa' ]
          dports: [ '33', '34' ]
          name: test
          weight: 56
